### APP ###
app:
  # Integrations
  integrations:
    backend:
      url: "${APP_INTEGRATIONS_BACKEND_URL}"
  # Security
  security:
    session:
      name: session
      cookie-name: SANDBOX_SESSION
    oauth2:
      name: oauth2
      callback-url: "http://localhost:8080/callback"
      provider:
        name: spring-authorization-server
        authorize-url: "${APP_SECURITY_OAUTH2_PROVIDER_URL}/oauth2/authorize"
        token-url: "${APP_SECURITY_OAUTH2_PROVIDER_URL}/oauth2/token"
        client-id: sandbox-oauth2-client
        client-secret: G4nd4lf
        default-scopes:
          - openid
          - profile
          - roles

### KTOR ###
ktor:
  # Development
  development: false
