### APP ###
app:
  id: ktor-kafka-streams-frontend-api
  kafka:
    producer:
      id: ktor-kafka-streams-frontend-api-producer
      brokers:
        - "localhost:9092"
      targetTopic: persons
    streams:
      id: ktor-kafka-streams-frontend-api-streams
      brokers:
        - "localhost:9092"
      sourceTopic: greetings
      stateStore: greetings
      processor: greetingProcessor

### KTOR ###
ktor:
  # Deployment
  deployment:
    port: 8080
  # Application
  application:
    modules:
      - com.onlyteo.sandbox.ApplicationKt.module