### APP ###
app:
  id: ktor-kafka-streams-backend
  kafka:
    streams:
      id: ktor-kafka-streams-backend-streams
      brokers:
        - "localhost:9092"
      sourceTopic: persons
      targetTopic: greetings
      stateStore: persons
      processor: personProcessor
      punctuatorSchedule: PT10S
      processingDelay: PT60S

### KTOR ###
ktor:
  # Deployment
  deployment:
    port: 8081
    host: 0.0.0.0
