### APP ###
app:
  id: ktor-kafka-streams-backend
  kafka:
    brokers:
      - "localhost:9092"
    streams:
      id: ktor-kafka-streams-backend-streams
      sourceTopic: persons
      targetTopic: greetings
      stateStore: greetings
      processor: greetingProcessor

### KTOR ###
ktor:
  # Deployment
  deployment:
    port: 8081
  # Application
  application:
    modules:
      - com.onlyteo.sandbox.ApplicationKt.module