### APP ###
app:
  # Kafka
  kafka:
    streams:
      id: ${app.id}-v2
      brokers:
        - "localhost:9092"
      sourceTopic: persons
      targetTopic: greetings

### KTOR ###
ktor:
  # Development
  development: true
