### APP ###
app:
  # Data source
  data-source:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sandbox
    username: sa
    password:
  # H2
  h2:
    console:
      enabled: true
      port: 8082

### KTOR ###
ktor:
  # Development
  development: true
