### RECEIVERS ###
receivers:
  # OTLP
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
    #  http:
    #    endpoint: 0.0.0.0:4318

### EXPORTERS ###
exporters:
  # OTLP
  otlp:
    endpoint: sandbox.grafana-tempo:4317
    tls:
      insecure: true
  # Debug
  debug:
    verbosity: detailed

### PROCESSORS ###
#processors:
#  # Filter
#  filter:
#    error_mode: ignore
#    traces:
#      span:
#        - IsMatch(attributes["url.path"], "/metrics")

### SERVICE ###
service:
  # Pipelines
  pipelines:
    traces:
      receivers:
        - otlp
  #    processors:
  #      - filter
      exporters:
        - otlp
  #  metrics:
  #    receivers:
  #      - otlp
  #    processors:
  #      - batch
  #    exporters:
  #      - otlp
  #  logs:
  #    receivers:
  #      - otlp
  #    processors:
  #      - batch
  #    exporters:
  #      - otlp
