receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
    #  http:
    #    endpoint: 0.0.0.0:4318
exporters:
  otlp:
    endpoint: sandbox.grafana-tempo:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
#processors:
#  filter:
#    error_mode: ignore
#    traces:
#      span:
#        - IsMatch(attributes["url.path"], "/metrics")
service:
  pipelines:
    traces:
      receivers: [ otlp ]
#      processors: [ filter ]
      exporters: [ otlp ]
  #  metrics:
  #    receivers: [otlp]
  #    processors: [batch]
  #    exporters: [otlp]
  #  logs:
  #    receivers: [otlp]
  #    processors: [batch]
  #    exporters: [otlp]
