global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: sandbox
    metrics_path: /metrics
    static_configs:
      - targets:
          - "sandbox.ktor-otel-observability-frontend-api:8080"
          - "sandbox.ktor-otel-observability-backend:8080"
  - job_name: tempo
    static_configs:
      - targets:
          - "sandbox.grafana-tempo:3200"
